#!/usr/bin/env python3
"""Render packaging/m5burner/cover.png, the M5Burner listing cover.

Composes the existing firmware screen renders from docs/ (generated by
docs/render_screens.py) onto a dark card with the product name. Pure Pillow,
no metadata in the output (M5Burner listings are public).
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "packaging" / "m5burner" / "cover.png"
SCREENS = [ROOT / "docs" / f"screen-{name}.png" for name in ("wait", "run", "done")]

W, H = 800, 500
BG = (11, 15, 20)
CARD = (20, 27, 36)
BLUE = (91, 123, 255)
GRAY = (154, 167, 180)
WHITE = (240, 244, 248)


def font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    candidates = [
        "/System/Library/Fonts/SFNS.ttf",
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf" if bold else "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
    ]
    for path in candidates:
        if Path(path).exists():
            try:
                return ImageFont.truetype(path, size)
            except OSError:
                continue
    return ImageFont.load_default()


def main() -> None:
    img = Image.new("RGB", (W, H), BG)
    draw = ImageDraw.Draw(img)
    draw.rounded_rectangle((24, 24, W - 24, H - 24), radius=28, fill=CARD)

    draw.text((56, 52), "TaskHub", font=font(56, bold=True), fill=WHITE)
    draw.text((56, 118), "for M5StickS3", font=font(26), fill=BLUE)
    draw.text(
        (56, 162),
        "Pocket status light for your AI coding agents.\nRUN · WAIT · DONE · FAIL, on your LAN.",
        font=font(20),
        fill=GRAY,
        spacing=6,
    )
    draw.text((56, 232), "Codex · Claude Code · Cursor · Cline · Gemini CLI · Copilot · Kimi · Manus", font=font(15), fill=GRAY)

    # Three device screens fanned along the bottom.
    x = 56
    y = 290
    for path in SCREENS:
        if not path.exists():
            continue
        screen = Image.open(path).convert("RGB").resize((208, 117))
        frame = Image.new("RGB", (screen.width + 12, screen.height + 12), (8, 10, 14))
        frame.paste(screen, (6, 6))
        img.paste(frame, (x, y))
        x += frame.width + 14

    draw.text((56, H - 62), "github.com/sheepxux/Taskhub-for-StickS3", font=font(16), fill=BLUE)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    clean = Image.new("RGB", img.size)
    clean.putdata(list(img.getdata()))
    clean.save(OUT, "PNG", optimize=True)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
